name: Build & Test
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: playground
          if-no-files-found: error
          path: |
            .playground/node_modules
            .playground/.nuxt
            node_modules
  Test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download the build folder
        uses: actions/download-artifact@v3
        with:
          name: playground
          path: |
            .playground/node_modules
            .playground/.nuxt
            node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm run lint
      - run: npm test

  Cypress:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download the build folder
        uses: actions/download-artifact@v3
        with:
          name: playground
          path: |
            .playground/node_modules
            .playground/.nuxt
            node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm start:cy
          browser: chrome
